# Uncomment this line to define a global platform for your project

platform :ios, "15.0"

target 'Demo' do

    pod 'MJRefresh'
    pod 'SDWebImage'

    pod 'LuaViewSDK', :path => '../../'
    pod 'liblua',  :path => '../../'
    
end

